### ISSUE TITLE
errors while running terraform plan -

### ISSUE THREAD

**Issue by suneelsunkara** [kumarvna/terraform-azurerm-caf-virtual-network-spoke#1]
When i run the terraform plan with variables.tf as attached in the zip file, i am getting below errors
[variables.zip](https://github.com/kumarvna/terraform-azurerm-caf-virtual-network-spoke/files/5807802/variables.zip)

Could you take a look?
Output:
terraform.exe plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.azurerm_resource_group.netwatch[0]: Refreshing state...

------------------------------------------------------------------------

Error: "resource_group_name" may only contain alphanumeric characters, dash, underscores, parentheses and periods

  on main.tf line 178, in resource "azurerm_private_dns_zone_virtual_network_link" "dzvlink":
 178: resource "azurerm_private_dns_zone_virtual_network_link" "dzvlink" {        

Error: "resource_group_name" may only contain alphanumeric characters, dash, underscores, parentheses and periods

  on main.tf line 203, in resource "azurerm_virtual_network_peering" "hub_to_spoke":
 203: resource "azurerm_virtual_network_peering" "hub_to_spoke" {

Error: expected "traffic_analytics.0.workspace_id" to be a valid UUID, got 

  on main.tf line 218, in resource "azurerm_network_watcher_flow_log" "nwflog":
 218: resource "azurerm_network_watcher_flow_log" "nwflog" {

Error: Can not parse "storage_account_id" as a resource id: Cannot parse Azure ID: parse "": empty url

  on main.tf line 218, in resource "azurerm_network_watcher_flow_log" "nwflog":
 218: resource "azurerm_network_watcher_flow_log" "nwflog" {

Error: expected "traffic_analytics.0.workspace_id" to be a valid UUID, got 

  on main.tf line 218, in resource "azurerm_network_watcher_flow_log" "nwflog":
 218: resource "azurerm_network_watcher_flow_log" "nwflog" {

Error: Can not parse "storage_account_id" as a resource id: Cannot parse Azure ID: parse "": empty url

  on main.tf line 218, in resource "azurerm_network_watcher_flow_log" "nwflog":
 218: resource "azurerm_network_watcher_flow_log" "nwflog" {

Error: Can not parse "storage_account_id" as a resource id: Cannot parse Azure ID: parse "": empty url

  on main.tf line 244, in resource "azurerm_monitor_diagnostic_setting" "vnet":
 244: resource "azurerm_monitor_diagnostic_setting" "vnet" {

Error: Can not parse "log_analytics_workspace_id" as a resource id: Cannot parse Azure ID: parse "": empty url

  on main.tf line 244, in resource "azurerm_monitor_diagnostic_setting" "vnet":
 244: resource "azurerm_monitor_diagnostic_setting" "vnet" {

Error: Can not parse "log_analytics_workspace_id" as a resource id: Cannot parse Azure ID: parse "": empty url

  on main.tf line 267, in resource "azurerm_monitor_diagnostic_setting" "nsg":
 267: resource "azurerm_monitor_diagnostic_setting" "nsg" {

Error: Can not parse "storage_account_id" as a resource id: Cannot parse Azure ID: parse "": empty url

Error: Can not parse "storage_account_id" as a resource id: Cannot parse Azure ID: parse "": empty url

Error: Can not parse "storage_account_id" as a resource id: Cannot parse Azure ID: parse "": empty url

  on main.tf line 267, in resource "azurerm_monitor_diagnostic_setting" "nsg":
 267: resource "azurerm_monitor_diagnostic_setting" "nsg" {

Error: Can not parse "log_analytics_workspace_id" as a resource id: Cannot parse Azure ID: parse "": empty url

  on main.tf line 267, in resource "azurerm_monitor_diagnostic_setting" "nsg":
 267: resource "azurerm_monitor_diagnostic_setting" "nsg" {

Error: Can not parse "storage_account_id" as a resource id: Cannot parse Azure ID: parse "": empty url

  on main.tf line 267, in resource "azurerm_monitor_diagnostic_setting" "nsg":
 267: resource "azurerm_monitor_diagnostic_setting" "nsg" {

**Comment by kumarvna** [comment]
seems to be an issue with the resource group name. please check the examples section to use the module.
